name: Node CI

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [8.16.2, 10.x, 12.x]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, deploy
      env:
        CI: true
        AIO_RUNTIME_AUTH: ${{ secrets.AIO__RUNTIME_AUTH }}
        AIO_RUNTIME_NAMESPACE: ${{ secrets.AIO__RUNTIME_NAMESPACE }}
        AIO_RUNTIME_APIHOST: ${{ secrets.AIO__RUNTIME_APIHOST }}
      run: |
        npm install
        npm run deploy
        npm run invoke
        npm run last-log
      
